# Shared Configuration for All Services
# This file is loaded by all services

# Common Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,env
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.diskspace.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# Common DevTools Configuration
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
