services:
  api-gateway:
    build: .
    container_name: api-gateway-app
    ports:
      - "8888:8080"
    environment:
      - USER_SERVICE_URL=http://user-service-app:8080
      - PRODUCT_SERVICE_URL=http://product-service:8080
      - ORDER_SERVICE_URL=http://order-service:8080
      - PAYMENT_SERVICE_URL=http://payment-service:8080
      - NOTIFICATION_SERVICE_URL=http://notification-service:8080
      - JWT_SECRET=mySecretKey123456789012345678901234567890
      - JWT_EXPIRATION=86400000
    networks:
      - microservices-network
      - user-service_user-service-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  microservices-network:
    driver: bridge
  user-service_user-service-network:
    external: true
