services:
  api-gateway:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway-app
    user: "1000:1000"  # Map to host user to avoid permission issues
    ports:
      - "8889:8080"
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src
      - ./build.gradle:/app/build.gradle
      - ./settings.gradle:/app/settings.gradle
      # Mount gradle cache to speed up builds
      - gradle-cache:/home/spring/.gradle
    environment:
      - USER_SERVICE_URL=http://user-service-app:8080  # Container name as hostname
      - PRODUCT_SERVICE_URL=http://product-service-app:8080
      - ORDER_SERVICE_URL=http://order-service-app:8080
      - PAYMENT_SERVICE_URL=http://payment-service-app:8080
      - NOTIFICATION_SERVICE_URL=http://notification-service-app:8080
      - JWT_SECRET=mySecretKey123456789012345678901234567890
      - JWT_EXPIRATION=86400000
    networks:
      - microservices-network  # Same shared network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  gradle-cache:
    driver: local

networks:
  microservices-network:
    external: true  # Use external shared network
