version: '3.8'
services:
  # Databases - Each service has its own database
  user-db:
    image: postgres:13
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
      - ./z-init-db/user_service_db.sql:/docker-entrypoint-initdb.d/user_service_db.sql
    networks:
      - microservices-network

  product-db:
    image: postgres:13
    environment:
      POSTGRES_DB: product_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  order-db:
    image: postgres:13
    environment:
      POSTGRES_DB: order_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  payment-db:
    image: postgres:13
    environment:
      POSTGRES_DB: payment_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  mongodb:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - microservices-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    networks:
      - microservices-network

  # Microservices
  user-service:
    build: ./user-service
    ports:
      - "8081:8080"
    depends_on:
      - user-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_service_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - microservices-network

  product-service:
    build: ./product-service
    ports:
      - "8082:8080"
    depends_on:
      - product-db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/product_service_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    ports:
      - "8083:8080"
    depends_on:
      - order-db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/order_service_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=password
    networks:
      - microservices-network

  payment-service:
    build: ./payment-service
    ports:
      - "8084:8080"
    depends_on:
      - payment-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment-db:5432/payment_service_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - microservices-network

  notification-service:
    build: ./notification-service
    ports:
      - "8085:8080"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongodb:27017/notifications
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=password
    networks:
      - microservices-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
      - notification-service
    networks:
      - microservices-network

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - microservices-network

volumes:
  user_db_data:
  product_db_data:
  order_db_data:
  payment_db_data:
  mongodb_data:

networks:
  microservices-network:
    driver: bridge