spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
    timeout: 60000
  cache:
    type: redis
    redis:
      time-to-live: 300000

server:
  port: 8080

logging:
  level:
    com.microservices.productservice: DEBUG