services:
  user-db:
    image: postgres:13
    container_name: user-service-db
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
      - ../z-init-db/user_service_db.sql:/docker-entrypoint-initdb.d/user_service_db.sql
    networks:
      - microservices-network  # Changed to shared network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d user_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: user-service-app
    user: "1000:1000"  # Map to host user to avoid permission issues
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src
      - ./build.gradle:/app/build.gradle
      - ./settings.gradle:/app/settings.gradle
      # Mount gradle cache to speed up builds
      - gradle-cache:/home/spring/.gradle
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-service-db:5432/user_service_db  # Using container name
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - microservices-network  # Changed to shared network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  user_db_data:
  gradle-cache:
    driver: local

networks:
  microservices-network:
    external: true  # Use external shared network
