spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password

server:
  port: 8080

logging:
  level:
    com.microservices.paymentservice: DEBUG